### ISSUE TITLE
Maven Central artifacts "not found"

### ISSUE THREAD

**Issue by miguno** [jodersky/sbt-gpg#9]
It seems as if the artifacts are listed in Maven Central, but attempting to download them (jar, pom) fails with a Not Found.

https://search.maven.org/search?q=g:io.crashbox%20AND%20a:sbt-gpg&core=gav

**Comment by jodersky** [comment]
Looks like it is due to a discrepancy between maven conventions and the way sbt appends version information to plugins. You can browse the archive here https://repo1.maven.org/maven2/io/crashbox/sbt-gpg_2.12_1.0/0.2.0/.
In case you're using the plugin within sbt, it should still find the correct jars nevertheless.

**Comment by miguno** [comment]
I have been debugging this issue with sbt version 1.2.7 (via homebrew) as well as with the sbt wrapper from https://github.com/paulp/sbt-extras, which is still on 0.13.  Perhaps that's the problem?

Because this line in `project/plugins.sbt` fails to work:

```
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.1")
```

The following line will find the sbt-gpg artifacts (sbt version hardwired to 1.0, Scala version to 2.12), but my local sbt versions are not compatible and will error out.

```
addSbtPlugin("io.crashbox" % "sbt-gpg" % "0.2.0", "1.0", "2.12")
```

**Comment by djspiewak** [comment]
sbt-extras isn't 0.13. It's going to use whatever you have in your `build.properties`. If you just use the following, what error do you get?

```sbt
addSbtPlugin("io.crashbox" % "sbt-gpg" % "0.2.0")
```

**Comment by miguno** [comment]
Thanks @djspiewak.

> sbt-extras isn't 0.13. It's going to use whatever you have in your build.properties.

My understanding was that sbt-extras does not support 1.x yet: https://github.com/paulp/sbt-extras/issues/216. Also, I do not set anything special in `build.sbt` with regards to sbt's version. The project itself is building against Scala 2.12 and 2.11 (see [WIP branch](https://github.com/miguno/akka-mock-scheduler/tree/develop-akka-update)).

> If you just use the following, what error do you get? [...]

I get the following with sbt-extras (`./sbt`) as well as with `sbt` (homebrew, sbt 1.2.7):

```
$ ./sbt deps
[...]
[info] Resolving io.crashbox#sbt-gpg;0.2.0 ...
[warn] 	module not found: io.crashbox#sbt-gpg;0.2.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/io.crashbox/sbt-gpg/scala_2.10/sbt_0.13/0.2.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.crashbox/sbt-gpg/scala_2.10/sbt_0.13/0.2.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/mnoll/.ivy2/local/io.crashbox/sbt-gpg/scala_2.10/sbt_0.13/0.2.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/crashbox/sbt-gpg_2.10_0.13/0.2.0/sbt-gpg-0.2.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/mnoll/.sbt/preloaded/io.crashbox/sbt-gpg/0.2.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/mnoll/.sbt/preloaded/io/crashbox/sbt-gpg_2.10_0.13/0.2.0/sbt-gpg-0.2.0.pom
[warn] ==== sbt-plugin-releases-repo: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io/crashbox/sbt-gpg_2.10_0.13/0.2.0/sbt-gpg-0.2.0.pom
[warn] ==== sbt-idea-repository: tried
[warn]   http://mpeltonen.github.io/maven/io/crashbox/sbt-gpg_2.10_0.13/0.2.0/sbt-gpg-0.2.0.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.crashbox#sbt-gpg;0.2.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		io.crashbox:sbt-gpg:0.2.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.crashbox:sbt-gpg:0.2.0 (scalaVersion=2.10, sbtVersion=0.13) (/Users/mnoll/git/akka-mock-scheduler/project/plugins.sbt#L25-26)
[warn] 		  +- default:akka-mock-scheduler-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: io.crashbox#sbt-gpg;0.2.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:320)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1555)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1551)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1586)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1584)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1589)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1583)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1606)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1533)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1485)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: io.crashbox#sbt-gpg;0.2.0: not found
```

**Comment by jodersky** [comment]
From these lines of the error report

> [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		io.crashbox:sbt-gpg:0.2.0 (scalaVersion=2.10, sbtVersion=0.13)

something is requesting sbt-gpg for sbt version 0.13, which does not exist (sbt-gpg only supports sbt >= 1)

My guess as to the cause of the version mismatch is that either:
1) sbt version 0.13 is in fact used. What's in your `project/build.properties` file, and what's the output of `sbt sbtVersion`?
2) sbt-extras is interfering

in case of 1), I would suggest to hardcode version 1.2.7 in `project/build.properties` and try again. In case of 2), unfortunately I can't help you, but I would strongly advise to disable sbt-extras. As per the open issue, it is not supported by sbt 1, however sbt 1 is required by sbt-gpg.

**Comment by djspiewak** [comment]
sbt-extras doesn't interfere here and it most definitely does support higher versions of SBT (I'm using it myself right now with 1.2.7). `project/build.properties` is where the problem is. SBT no longer *allows* you to not have this file, so it's there and it has some contents. Those contents are your SBT version.

**Comment by miguno** [comment]
The issue was sorted out via `project/build.properties`.  I blame my rusty sbt knowledge!

```shell
$ cat project/build.properties
sbt.version=1.2.7
```

Thanks both of you for helping me sorting this out!

**Comment by miguno** [comment]
And thanks to @jodersky for your work on sbt-gpg in the first place.  Much appreciated!

**Comment by dwijnand** [comment]
Note the presence of sbt.version in project/build.properties is enforced in sbt 1.x... by writing it 😉.
